//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentID { get; set; }
        public int DomainID { get; set; }
        public string Descriptor { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTestKit { get; set; }
        public string Supplier { get; set; }
        public string SupplierCode { get; set; }
        public string EquipmentClass { get; set; }
        public string SmallImage { get; set; }
        public string MediumImage { get; set; }
        public string LargeImage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
