//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp
    {
        public int GroupID { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string ValueCode { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
        public string ValueDescription { get; set; }
        public string OwnerFieldName { get; set; }
        public string OwnerValue { get; set; }
        public Nullable<bool> DefaultValue { get; set; }
        public Nullable<bool> SystemRequired { get; set; }
        public Nullable<bool> Aliased { get; set; }
        public string ValueForAction { get; set; }
        public byte[] RecordLastUpdated { get; set; }
    }
}
