//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LookUp> LookUps { get; set; }
        public DbSet<SampleTransportCondition> SampleTransportConditions { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<TestRequirement> TestRequirements { get; set; }
        public DbSet<TestSample> TestSamples { get; set; }
        public DbSet<TestStep> TestSteps { get; set; }
        public DbSet<TestSynonym> TestSynonyms { get; set; }
        public DbSet<TestTutorialStep> TestTutorialSteps { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
    }
}
