//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestSamples = new HashSet<TestSample>();
            this.TestSteps = new HashSet<TestStep>();
            this.TestTutorialSteps = new HashSet<TestTutorialStep>();
            this.TestRequirements = new HashSet<TestRequirement>();
        }
    
        public int TestID { get; set; }
        public int DomainID { get; set; }
        public int TestCategoryID { get; set; }
        public string TestCode { get; set; }
        public string Description { get; set; }
        public string GuideVersion { get; set; }
        public string HelpText { get; set; }
        public string HelpImage { get; set; }
        public Nullable<decimal> EstimatedDuration { get; set; }
        public string Laboratory { get; set; }
        public string ReferenceLaboratory { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> LastUpdateUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
    
        public virtual ICollection<TestSample> TestSamples { get; set; }
        public virtual ICollection<TestStep> TestSteps { get; set; }
        public virtual ICollection<TestTutorialStep> TestTutorialSteps { get; set; }
        public virtual ICollection<TestRequirement> TestRequirements { get; set; }
    }
}
