//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSample
    {
        public TestSample()
        {
            this.SampleTransportConditions = new HashSet<SampleTransportCondition>();
        }
    
        public int SampleId { get; set; }
        public int TestID { get; set; }
        public int EquipmentID { get; set; }
        public int SmaplesRequired { get; set; }
        public string SampleClassRule { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> MinimumQuantity { get; set; }
        public Nullable<decimal> IdealQuantity { get; set; }
        public Nullable<decimal> MicroQuantity { get; set; }
        public string SampleType { get; set; }
        public string AnalysisSampleType { get; set; }
    
        public virtual ICollection<SampleTransportCondition> SampleTransportConditions { get; set; }
        public virtual Test Test { get; set; }
    }
}
