//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSynonym
    {
        public int SynonymId { get; set; }
        public int TestID { get; set; }
        public string PrimaryCode { get; set; }
        public string Code { get; set; }
        public string AlternateName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
