//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStep
    {
        public int StepID { get; set; }
        public int TestID { get; set; }
        public int CompetencyLevelID { get; set; }
        public string StepName { get; set; }
        public int StepOrder { get; set; }
        public string StepDescription { get; set; }
        public string ImageUrl { get; set; }
        public string VideoUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
